[package]
name = "hash-game"
version = "0.1.0"
authors = ["Hermano <srhermanodecastro@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reader = "0.1.1"